### ISSUE TITLE
'disconnected' event is not firing

### ISSUE THREAD

**Issue by MaybeRex** [RIAEvangelist/node-phidget-API#20]
'disconnected' is not firing  when disconnected

**Comment by RIAEvangelist** [comment]
The disconnected event does infact fire when disconnecting from the phidget.

The detached event fires when the phidget is detached from the computer as per the phidget spec.

is this not well documented? @MaybeRex and @rajivsavroop

**Comment by RIAEvangelist** [comment]
When looking at the documentation it seems pretty clear.

Also there are other events as well, the added and removed which work the same as attached and removed.

RTFM on this one?

**Comment by RIAEvangelist** [comment]
Although I do notice the only time the attached and detached events are fired is on the manager. I'll fix that. Still, disconnected does fire as the documentation states, when the socket is closed or lost.
