### ISSUE TITLE
Which nw version is compatible?

### ISSUE THREAD

**Issue by Imadeanaccountforthis** [RIAEvangelist/node-phidget-API#56]
phidgetapi doesn't seem to work with the latest version of nw.js, which would be the latest version compatible with it? 
in nw 0.16 I get a "cannot read property split of undefined" for 
`var tag2=phidget.data.board.Tag2.split('/');`
in lib/RFID.js., same kind of thing goes for interfacekit.js,I'm trying to take a look at it but I have close to zero javascript experience (first time user)

**Comment by MaybeRex** [comment]
This api won't work with the latest builds of node.js, but I am currently working on getting up to speed.  node v.0.12 works perfectly so if you revert back to a nw version that runs that it should work

**Comment by RIAEvangelist** [comment]
Object.observe was deprecated as of node v4 were working on an upgrade
