### ISSUE TITLE
Unable to connect to remote webservice

### ISSUE THREAD

**Issue by openStove** [RIAEvangelist/node-phidget-API#57]
I tried to connect to another webservice : 

```
spatial.connect({"host":"192.168.178.30"})
```

conn=spatial.connect({"host":"192.168.178.30"})
        node.log("connecting " + JSON.stringify(spatial,null,2))

But everything remain on default params :

``` json
    "params": {
      "type": "PhidgetSpatial",
      "host": "localhost",
      "port": 5001,
      "version": "1.0.10",
      "password": false,
      "rawLog": false,
      "serial": false,
      "label": false,
      "rate": 8
    }
```

**Comment by RIAEvangelist** [comment]
if you are using the version that is in npm it should work

make sure you have started the phidgetwebservice21

can you link me to your repo?
