### ISSUE TITLE
Object.observe is not a function

### ISSUE THREAD

**Issue by sops21** [RIAEvangelist/node-phidget-API#59]
Running Node 6.9.1

When following the [InterfaceKit Example ](https://github.com/RIAEvangelist/node-phidget-API/blob/master/docs/InterfaceKit.md)

I'm getting the following error: 

`/Users/***/Projects/***/***/node_modules/phidgetapi/lib/InterfaceKit.js:226
    Object.observe(
           ^

TypeError: Object.observe is not a function
    at new InterfaceKit (/Users/***/Projects/***/***/node_modules/phidgetapi/lib/InterfaceKit.js:226:12)
    at Object.<anonymous> (/Users/***/Projects/***/***/app.js:10:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jasonsmall/Projects/busserver/busserver/bin/www:7:28)`

Any thoughts?

**Comment by RIAEvangelist** [comment]
I guess it finally got removed as deprecated in the latest node.

We'll have to update the code base for the latest node.

**Comment by nexflo** [comment]
Is this happening? Not working on current installs - so an update would be rad 👍

**Comment by nexflo** [comment]
new JS Proxy function should probably do it?

**Comment by nexflo** [comment]
npm install object.observe

require('object.observe');

As a quick fix for everyone. Could probably just integrate this into main package as a PR as its a polyfill and will work for old and new browsers. Not the most elegant solution as its deprecated but it makes it work.
Cleaner to rewrite with Proxies. (wont work on old version then tho?)

**Comment by RIAEvangelist** [comment]
this could be integrated into the module as a dep if you have time. I will release if your submit PR.

**Comment by nexflo** [comment]
#62 and #63 are in. Integrated as dependency.
I would propose to push these to npm as well - after being tested - as the current version is unusable for all node version released over a year.

Best

**Comment by RIAEvangelist** [comment]
fixed by #62 & #63

**Comment by RIAEvangelist** [comment]
published and added as contributor on [phidgetapi npm module](https://www.npmjs.com/package/phidgetapi)
